core_telecom_dbt:
  target: ci
  outputs:
    ci:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT', 'dummy') }}"
      user: "{{ env_var('SNOWFLAKE_USER', 'dummy') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD', 'dummy') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'DUMMY_ROLE') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'DUMMY_DB') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'DUMMY_WH') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA', 'CI_SCHEMA') }}"
      threads: 1
