core_telecom_dbt:
  target: ci
  outputs:
    ci:
      type: snowflake
      account: "dummy"
      user: "dummy"
      password: "dummy"
      role: "DUMMY_ROLE"
      database: "DUMMY_DB"
      warehouse: "DUMMY_WH"
      schema: "CI_SCHEMA"
      threads: 1
