USE DATABASE CORE_TELECOM_DB;

CREATE OR REPLACE STORAGE INTEGRATION s3_int
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = '${AWS_SNOWFLAKE_ROLE_ARN}'
  STORAGE_ALLOWED_LOCATIONS = ('${BRONZE_S3_BUCKET}');

  DESC STORAGE INTEGRATION s3_int;